CREATE TABLE tenants (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255) NOT NULL,
    slug       VARCHAR(255) NOT NULL UNIQUE,
    created_at timestamptz  NOT NULL DEFAULT now(),
    updated_at timestamptz  NOT NULL DEFAULT now()
);

CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id     BIGINT       NOT NULL REFERENCES tenants (id),
    full_name     VARCHAR(255) NOT NULL,
    email         VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role          VARCHAR(16)  NOT NULL,
    created_at    timestamptz  NOT NULL DEFAULT now(),
    updated_at    timestamptz  NOT NULL DEFAULT now(),
    CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE INDEX idx_users_tenant ON users (tenant_id);

CREATE TABLE services (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id        BIGINT         NOT NULL REFERENCES tenants (id),
    name             VARCHAR(255)   NOT NULL,
    description      VARCHAR(500),
    duration_minutes INTEGER        NOT NULL,
    price            NUMERIC(10, 2) NOT NULL,
    created_at       timestamptz    NOT NULL DEFAULT now(),
    updated_at       timestamptz    NOT NULL DEFAULT now()
);

CREATE INDEX idx_services_tenant ON services (tenant_id);

CREATE TABLE appointments (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id      BIGINT       NOT NULL REFERENCES tenants (id),
    service_id     BIGINT       NOT NULL REFERENCES services (id),
    staff_id       BIGINT       NOT NULL REFERENCES users (id),
    customer_name  VARCHAR(255) NOT NULL,
    customer_email VARCHAR(255),
    customer_phone VARCHAR(255),
    start_at       timestamptz  NOT NULL,
    end_at         timestamptz  NOT NULL,
    status         VARCHAR(16)  NOT NULL,
    created_at     timestamptz  NOT NULL DEFAULT now(),
    updated_at     timestamptz  NOT NULL DEFAULT now()
);

CREATE INDEX idx_appointments_tenant ON appointments (tenant_id);
CREATE INDEX idx_appointments_staff ON appointments (staff_id);
CREATE INDEX idx_appointments_window ON appointments (staff_id, start_at, end_at);
